  - name: Installing the mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Starting and enabling mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Changing the default root password of mysql
    ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"

